name: Python CI
author: mrcointreau
description: Audit, lint, test, and build Python projects using uv

inputs:
  python-version:
    description: Python version
    required: false
    default: "3.12"
  working-directory:
    description: Working directory
    required: false
    default: "."
  skip-audit:
    description: Skip security audit step
    required: false
    default: "false"
  skip-lint:
    description: Skip linting step
    required: false
    default: "false"
  skip-test:
    description: Skip test step
    required: false
    default: "false"
  skip-build:
    description: Skip build step
    required: false
    default: "false"
  pre-test-script:
    description: Script to run before tests
    required: false
    default: ""
  install-command:
    description: "Install command to run"
    required: false
    default: "uv sync"
  lint-command:
    description: "Lint command to run"
    required: false
    default: "uv run ruff check ."
  test-command:
    description: "Test command to run"
    required: false
    default: "uv run pytest"
  build-command:
    description: "Build command to run"
    required: false
    default: "uv build"

outputs:
  audit-outcome:
    description: Outcome of the audit step (success, failure, skipped)
    value: ${{ steps.audit.outcome }}
  lint-outcome:
    description: Outcome of the lint step (success, failure, skipped)
    value: ${{ steps.lint.outcome }}
  test-outcome:
    description: Outcome of the test step (success, failure, skipped)
    value: ${{ steps.test.outcome }}
  build-outcome:
    description: Outcome of the build step (success, failure, skipped)
    value: ${{ steps.build.outcome }}

runs:
  using: composite
  steps:
    - name: Setup Python
      uses: actions/setup-python@v5.6.0 # v5.6.0
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install uv
      uses: astral-sh/setup-uv@d4b2f3b6ecc6e67c4457f6d3e41ec42d3d0fcb86 # v5.4.2
      with:
        enable-cache: true

    - name: Install Dependencies
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: ${{ inputs.install-command }}

    - name: Audit
      id: audit
      if: inputs.skip-audit != 'true'
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: uvx pip-audit --strict --progress-spinner=off

    - name: Lint
      id: lint
      if: inputs.skip-lint != 'true'
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        ${{ inputs.lint-command }}

    - name: Pre-test Script
      if: inputs.pre-test-script != ''
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: ${{ inputs.pre-test-script }}

    - name: Test
      id: test
      if: inputs.skip-test != 'true'
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        ${{ inputs.test-command }}

    - name: Build
      id: build
      if: inputs.skip-build != 'true'
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        ${{ inputs.build-command }}
